Fix minor bugs
SteamingMutt/DiscordFeedback pull request #10
Opened 2017-03-25 13:50 UTC by nullpixel1

2017-03-25 13:52 UTC, Dougley requested changes

2017-03-25 13:52 UTC, SteamingMutt commented on Commands/Commands/utils.js
>                          message.reply('Thanks for your report! We\'ve asked the custodians to review your report, you should hear from us soon!')
Add it here too then

2017-03-25 13:53 UTC, nullpixel1 commented on Commands/Commands/utils.js
>                          message.reply('Thanks for your report! We\'ve asked the custodians to review your report, you should hear from us soon!')
Thought it was left like that intentionally. Can add it, sure

2017-03-27 15:58 UTC, Dougley approved these changes

2017-03-27 15:58 UTC, merged