!status
SteamingMutt/DiscordFeedback pull request #103
Opened 2017-08-17 19:34 UTC by LW001

I've finally added !status. yay.
What differenciates this from my other stuff is that it's [fully tested](https://dabbit.uservoice.com/forums/598597-general/suggestions/19700419-hey#{toggle_previous_statuses}).

How to use:
**!status** _URL/Link/UVRegex_ _Name of status flag or none to not set a status_ _Message to add to it_

Status flag should work with the name of any flag, if it's not a valid flag name there just won't be a status changed but still a response created.

2017-08-18 14:22 UTC, Dougley requested changes

2017-08-18 14:22 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +            author: {
A creator object is not guaranteed (loluv)

2017-08-18 14:23 UTC, SteamingMutt commented
Also, what would the exact syntax be? Please provide a working example.

2017-08-18 20:13 UTC, LW001 commented
`!status https://dabbit.uservoice.com/forums/598597-general/suggestions/20603587-create-a-status-reaction planned This will be added at some point.`

Probably will be changed to
`!status https://dabbit.uservoice.com/forums/598597-general/suggestions/20603587-create-a-status-reaction planned | This will be added at some point` though

2017-08-19 18:47 UTC, LW001 commented
New usage
`!status 19700419 | completed | we needed pipes`

2017-08-29 19:58 UTC, RSNFreud commented
*wonders how long this will take to get passed*

2017-08-29 19:59 UTC, RSNFreud commented
Also mandatory **LWWarez** flag.

2017-09-04 16:45 UTC, LW001 commented
Yo what's the plan with this now?

2017-09-04 16:53 UTC, SteamingMutt commented
soon™️, haven't had the time to properly review.

2017-09-28 17:17 UTC, RSNFreud commented
1 month later...

2017-09-28 20:34 UTC, SirDoctors commented
@RSNFreud please stop adding comments like this, we are aware of all the pull requests, we are currently working on a full rewrite of the bot and therefore are holding of on most pr's for the moment.

2017-09-28 20:36 UTC, RSNFreud commented
Ahh sorry. Wasnt aware of that cause.. yknow.. banned

2017-10-06 15:11 UTC, closed without merging