Command rate limiting!
SteamingMutt/DiscordFeedback pull request #109
Opened 2017-08-19 22:29 UTC by LW001

Basically it saves the time when you do a command and checks whether the cooldown from limit.js in ms has passed since then.

TL;DR: limit.js is the millisecond values for each permission level for each command.

2017-08-19 22:33 UTC, SirDoctors commented
Do this based on develop please.

2017-08-19 22:40 UTC, SirDoctors commented on limit.js
> +    stats: 0
could these not be 0? Please increase to 1s

2017-08-19 22:40 UTC, SirDoctors commented on limit.js
> +    stats: 0
same here

2017-08-30 23:43 UTC, SteamingMutt commented
Some command should have a global cooldown too, so you can't use multiple accounts to spam.

2017-08-31 10:40 UTC, LW001 commented
That would so get annoying though, imagine two people wanting to do dupes
at the same time
Am 31.08.2017 01:43 schrieb "Remco" <notifications@github.com>:

> Some command should have a global cooldown too, so you can't use multiple
> accounts to spam.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SteamingMutt/DiscordFeedback/pull/109#issuecomment-326149218>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXOd1IdNHozIMGdsT2Vok7HXlA8kag_Tks5sdfO3gaJpZM4O8day>
> .
>

2017-08-31 10:51 UTC, SteamingMutt commented
It wouldn't need to be overly huge, think a global 500ms timeout for submit.

2017-09-05 17:09 UTC, nullpixel submitted a review, later dismissed

2017-09-05 17:09 UTC, nullpixel commented on index.js
> +var limits = require('./limit.js')
constant pls

2017-09-07 08:14 UTC, Dougley requested changes

2017-09-07 08:14 UTC, SteamingMutt commented on index.js
> +        if (limits.global[cmd] && Date.now() - commandLimitMap.get('global') < limits.global[cmd] && level !== 2) {
`commandLimitMap.get(msg.author.id+cmd)` is not guaranteed to return a value, but this is assumig it is.

2017-10-06 15:11 UTC, closed without merging