promise chain dupe
SteamingMutt/DiscordFeedback pull request #110
Opened 2017-08-21 09:05 UTC by LW001

2017-08-21 18:51 UTC, ThaTiemsz requested changes

2017-08-21 18:51 UTC, ThaTiemsz commented on Commands/Commands/queue.js
> +        .then((data2) => msg.reply(`this will result in the following card.\n__Are you sure this is correct?__ (yes/no)`, false, {
These parentheses are reluctant

2017-08-21 18:51 UTC, ThaTiemsz commented on Commands/Commands/queue.js
> +        }).then(() => wait(bot, msg)
Move this to a new line, don't forget the closing `)`

2017-08-21 18:51 UTC, ThaTiemsz commented on Commands/Commands/queue.js
> +        })))).catch((e) => {
What in the world is this

2017-08-21 18:51 UTC, ThaTiemsz commented on Commands/Commands/queue.js
> +        ).catch((e) => {
­

2017-09-05 17:19 UTC, nullpixel requested changes
see tiemens review

2017-09-09 03:33 UTC, closed without merging

2017-09-09 03:35 UTC, SirDoctors commented
Closed in favor of ignoring fixing the current MB for doing the rewrite version and fixing up current MB.