[WIP] massive rewrite (help and comments welcome)
SteamingMutt/DiscordFeedback pull request #18
Opened 2017-06-09 19:35 UTC by devsnek

woo

2017-06-09 19:43 UTC, Dougley requested changes

2017-06-09 19:43 UTC, SteamingMutt commented on index.js
> +const Discord = require('discord.js');
no

2017-06-09 19:43 UTC, SteamingMutt commented on package.json
> +      "name": "snek <me@gus.host>"
no

2017-06-09 19:43 UTC, SteamingMutt commented on package.json
> +    "discord.js": "^11.1.0",
no

2017-06-09 19:43 UTC, SteamingMutt commented on util/MessageAsk.js
> +const Discord = require('discord.js');
no

2017-06-09 19:43 UTC, SteamingMutt commented on util/UserVoice.js
> +const snekfetch = require('snekfetch');
no, use superagent.

2017-06-09 19:43 UTC, SteamingMutt commented on .gitignore
> +old
what

2017-06-23 18:06 UTC, SirDoctors commented
@devsnek Please fix the outlined problems and update to the current revision of the master branch, as there is several files in conflict.

2017-06-23 18:34 UTC, nullpixel commented
Will reopen if you begin work

2017-06-23 18:34 UTC, closed without merging