Commenting from queue
SteamingMutt/DiscordFeedback pull request #22
Opened 2017-06-10 07:34 UTC by LW001

As per Prime Dabbster's request, here's the ability to comment through the queue. Shout at me for errors.

https://trello.com/c/HfjzMHPX

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:39 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 07:40 UTC, LW001 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[admin-queue] Add comment reaction](https://trello.com/c/HfjzMHPX/65-admin-queue-add-comment-reaction)

2017-06-10 10:20 UTC, Dougley requested changes

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                  }
Format please

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                          cBack({
Don't callback, this is only for actual commands

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                            title: entities.decode(data.comment.suggestion.title),
Don't embed, this will only cause more clutter

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                }
Format please

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                        msg.reply('your comment was added.', false, {
Don't embed

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                        msg.reply('your comment was added.', false, {
Don't embed

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                        cBack({
Don't callback

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +        resolve(c)
Resolve with c.message.content

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                  fn: function (bot, msg, suffix, uvClient, cBack) {
Nice copy-paste, fn is specific for commands

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                    fn: function (bot, msg, suffix, uvClient, cBack) {
Nice copy-paste, fn is specific for commands

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                    bot.Messages.deleteMessages([aacmsg.id, msg.id], bot.Channels.find(c => c.name === 'admin-queue').id)
Why are you deleting the report?

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                    msg.reply('You took too long to comment, the operation has been cancelled.').then(msgdelet => {
msg is the bots message, send a regular message

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                              cause: 'comment_add',
This needs its own case

2017-06-10 10:20 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                            cause: 'comment_add',
Own case required

2017-06-12 09:40 UTC, LW001 commented
Kinda won't be able to recover that repo, http://imgur.com/a/9CiLZ

Closing PR and reopening it later today, sorry for the inconvenience.

2017-06-12 09:40 UTC, closed without merging