Added !status
SteamingMutt/DiscordFeedback pull request #27
Opened 2017-06-10 19:53 UTC by LW001

As described in https://trello.com/c/Do2gYoM4/.

Using the command works the following way:
`!status <ID/LINK> <NEW STATUS> <COMMENT>`
* ID/LINK works using the magical UVRegex(TM)
* NEW STATUS accepts the following values:
`review, re, under review, ur, u, planned, plan, pl, p, started, start, completed, complete, co, c, declined, decline, de, d`
* COMMENT accepts a comment to be added, also filtering out pipes.

UV endpoint: https://developer.uservoice.com/docs/api/reference/#_api_v1_forums_forum_id_suggestions_suggestion_id_respond_put

I actually ran a syntax check this time, are you proud yet

2017-06-10 21:56 UTC, Dougley requested changes

2017-06-10 21:56 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +        if (statusname === 'review' || statusname === 're' || statusname === 'under review' || statusname === 'ur' || statusname === 'u') statusid = '1707873'
Use a regex

2017-06-11 10:17 UTC, Dougley requested changes
Last nitpick before I'll merge this

2017-06-11 10:17 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +        let grabstatusidfromhere = statncontent.toLowercase().match(grabidregex)
Use a case insensitive regex instead

2017-06-11 10:17 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +        let grabstatusidfromhere = statncontent.toLowercase().match(grabidregex)
Use a case insensitive regex instead

2017-06-11 19:11 UTC, LW001 commented
I fucked this one up quite a ton, cant edit it anymore because I deleted the repo, trying to get that fixed lul

2017-06-12 09:39 UTC, LW001 commented
Kinda won't be able to recover that repo, http://imgur.com/a/9CiLZ

Closing PR and reopening it later today, sorry for the inconvenience.

2017-06-12 09:39 UTC, closed without merging