Recreated  PR 27
SteamingMutt/DiscordFeedback pull request #29
Opened 2017-06-12 17:09 UTC by LW001

RE #27 

As described in https://trello.com/c/Do2gYoM4/.

Using the command works the following way:
`!status <ID/LINK> <NEW STATUS> <COMMENT>`

ID/LINK works using the magical UVRegex(TM)
NEW STATUS accepts the following values:
review, re, under review, ur, u, planned, plan, pl, p, started, start, completed, complete, co, c, declined, decline, de, d
COMMENT accepts a comment to be added, also filtering out pipes.
UV endpoint: https://developer.uservoice.com/docs/api/reference/#_api_v1_forums_forum_id_suggestions_suggestion_id_respond_put

2017-06-12 18:41 UTC, nullpixel requested changes
picky, but will improve code

2017-06-12 18:41 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +        else if (statusname.match(/(none|x|1)/)) { statusid = null; statusname = 'None'; }
this if statement is a bit eh, could this be refined?

2017-06-12 18:41 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +        if (parts === null) {
make this `id = parts === null ? idt : parts[2]` or `id = (parts && parts[2]) || idt`

2017-06-12 18:41 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +        let content = grabstatusidfromhere[1]
this variable name is too verbose. Use camel case.

2017-06-12 18:41 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +          msg.reply('The suggestion ' + uvurl + ' has been successfully updated to `' + statusname + '`').then(scssmsg => {
picky, but use backticks and ${}

2017-06-20 08:17 UTC, SteamingMutt commented
Closing this, superseded by #35

2017-06-20 08:17 UTC, closed without merging