Getting rid of every muppet using f1
SteamingMutt/DiscordFeedback pull request #30
Opened 2017-06-12 17:31 UTC by LW001

TODO: Getting rid of every :report: in the feed when :reported: gets shown, where's that bug pls help

2017-06-13 18:28 UTC, SirDoctors commented
![](https://cdn.discordapp.com/emojis/296752137935912960.png)

2017-06-14 07:44 UTC, Dougley requested changes

2017-06-14 07:44 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                      var muppetsArr = msg.fetchReactions({id: '296752137935912960', name: 'f1'}, bot.User) // muppetsArr => People trying to be funny by reacting to f1
Wrong usage of the [`fetchReations()` function](http://qeled.github.io/discordie/#/docs/IMessage?p=IMessage%23fetchReactions&_k=cgymn2)

2017-06-23 18:21 UTC, SirDoctors commented
Fix file conflicts please

2017-07-06 14:41 UTC, nullpixel submitted a review, later dismissed
please resolve all merge conflicts

2017-07-06 17:56 UTC, SirDoctors commented
Fixed merge conflicts

2017-07-09 18:19 UTC, SteamingMutt commented
The diff for this PR is empty, if you still want this merged, I'd suggest making a new PR.

2017-07-09 18:19 UTC, closed without merging