Fix another error that wasn't really an error
SteamingMutt/DiscordFeedback pull request #31
Opened 2017-06-13 19:18 UTC by SirDoctors

404 caused by user input and not related to the bot isn't an error, boi

2017-06-13 19:26 UTC, Dougley requested changes

2017-06-13 19:26 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +              setTimeout(() => bot.Messages.deleteMessages([o.id, msg.id], bot.Channels.find(c => c.name === 'admin-queue').id), config.timeouts.messageDelete)
- Supply the actual message objects, so you can leave the channel ID out.
- Format please.

2017-06-13 19:27 UTC, LW001 commented on Commands/Commands/queue.js
> +        bot.Channels.find(c => c.name === 'admin-queue').sendMessage('That suggestion doesn\'t seems to exist, (someone must have beat you too it).').then(o => {
beat you **to** it pls

2017-06-13 19:29 UTC, SirDoctors commented on Commands/Commands/queue.js
> +              setTimeout(() => bot.Messages.deleteMessages([o.id, msg.id], bot.Channels.find(c => c.name === 'admin-queue').id), config.timeouts.messageDelete)
I was just copy pasting from another admin-queue reponse

2017-06-14 07:38 UTC, Dougley requested changes

2017-06-14 07:38 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +        bot.Channels.find(c => c.name === 'admin-queue').sendMessage('That suggestion doesn\'t seems to exist, (someone must have beat you to it).').then(o => {
`doesn't seem to`

2017-06-23 17:52 UTC, SirDoctors commented
Unfortunately with all the work on master and me not being at my main machine (on laptop) I had to redo this pr without the formatting fixes. Otherwise this should be good to land in master.

2017-06-23 18:07 UTC, Dougley requested changes

2017-06-23 18:07 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +              setTimeout() => o.delete()
Syntax error

2017-06-23 18:07 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +            logger.log(bot, {
Indent using 2 spaces

2017-06-23 18:12 UTC, SirDoctors commented on Commands/Commands/queue.js
> +              setTimeout() => o.delete()
Where?

2017-06-23 18:13 UTC, SirDoctors commented on Commands/Commands/queue.js
> +            logger.log(bot, {
Looks awful, but ok

2017-06-23 18:14 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +              setTimeout() => o.delete()
`setTimeout(() => o.delete(), config.timeouts.whatever)`

2017-06-24 14:55 UTC, SirDoctors commented
Yo, I fixed the two things you pointed out, it good now?

2017-06-24 15:01 UTC, merged