!info command
SteamingMutt/DiscordFeedback pull request #32
Opened 2017-06-13 21:13 UTC by LW001

So I made a !info command which takes either Username#Discrim, a mention or even a discord ID and gives you info on that user on UV. It even lets you get their UV profile by Discord User ID if they arent on the server.
Even better it shouldn't have syntax errors because I used Visual Studio now
Even better I might add it showing stuff like the latest Upvote and Suggestion
EEEEEven better you get to test it because I can't :^)

2017-06-13 21:33 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +              color: fc9822,
This should be an integer

2017-06-13 21:33 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +              color: fc9822,
Agreed, this isn't a valid color

2017-06-13 21:33 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +            let link = entities.decode(data.user.url)
Indent more pls

2017-06-13 21:34 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +              if (userid == member.id) let dcuser = `${member.username}#${member.discriminator}`
`let` can't be in a single line if statement

2017-06-13 21:35 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +		setTimeout(bot.deleteMessages([msg,errMsg], msg.channel)),config.timeouts.errorMessageDelete
One ) too many, one too short

`setTimeout(bot.deleteMessages([msg,errMsg], msg.channel), config.timeouts.errorMessageDelete)`

2017-06-13 21:36 UTC, ThaTiemsz reviewed
­

2017-06-13 21:37 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +		setTimeout(bot.deleteMessages([msg,errMsg], msg.channel)),config.timeouts.errorMessageDelete
No, you can't bulk delete a single message

2017-06-13 21:43 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +		setTimeout(bot.deleteMessages([msg,errMsg], msg.channel)),config.timeouts.errorMessageDelete
Yeah. I was only fixing the syntax, didn't really read the code tbh, it's late ok

2017-06-14 07:46 UTC, Dougley requested changes

2017-06-14 07:46 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +    let mentions = msg.mentions()
`msg.mentions` is not a function, it's an attribute.

2017-06-15 20:22 UTC, ThaTiemsz reviewed
See comments I guess

2017-06-15 20:22 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +              latestSuggTitle = latestSugg.decode(latestSugg.suggestion.title)
Same here.

2017-06-15 20:22 UTC, ThaTiemsz commented on Commands/Commands/uservoice.js
> +              upLink = suggestion.decode(suggestion.url)
This most likely won't work.

2017-07-04 08:38 UTC, Dougley approved these changes

2017-07-04 08:40 UTC, SteamingMutt commented
Squashing this into develop

2017-07-04 08:40 UTC, merged