Timeout removing messages
SteamingMutt/DiscordFeedback pull request #4
Opened 2017-02-24 19:25 UTC by nullpixel1

- Fixes a bug where some messages would not be removed
- Times out deleting messages (dabbit request)
- Wait for the bot's message to be removed before removing the user's message

2017-02-24 19:31 UTC, Dougley requested changes

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +              messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +              messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +              messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +            messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +        messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +          messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +              messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +              messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +            messge.delete()
messge

2017-02-24 19:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +          messge.delete()
messge

2017-02-24 19:34 UTC, nullpixel1 commented
dammit, fixing

2017-02-24 19:44 UTC, Dougley requested changes

2017-02-24 19:44 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +            message.reply('You need to be an admin to approve this report.').then(delay(15000)).then((deletThis) => {
This doesn't work, this way you're passing the function as an argument to the anonymous function to the chain.

```js
.then((msg) => {
  message.delete()
  deletThis(msg)
})
```

2017-02-24 19:45 UTC, nullpixel1 commented on Commands/Commands/utils.js
> +            message.reply('You need to be an admin to approve this report.').then(delay(15000)).then((deletThis) => {
oh, right. didn't think of that. thanks 👍

2017-02-24 19:56 UTC, nullpixel1 commented
@SteamingMutt Should all be fixed now :)

2017-02-24 19:59 UTC, Dougley requested changes

2017-02-24 19:59 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +  return function(arg){
Why return 2 function statements if you don't do anything with it? Just return the promise.

2017-02-24 20:10 UTC, Arzte requested changes

2017-02-24 20:10 UTC, SirDoctors commented on Commands/Commands/utils.js
> +            message.reply('You need to be an admin to approve this report.').then(delay(15000)).then((msg) => {
can you make the ``delay()`` time into a config option?

2017-02-24 20:13 UTC, nullpixel1 commented on Commands/Commands/utils.js
> +            message.reply('You need to be an admin to approve this report.').then(delay(15000)).then((msg) => {
Sure; was debating doing this out of the box, but now you asked I can

2017-02-24 20:31 UTC, Dougley requested changes

2017-02-24 20:31 UTC, SteamingMutt commented on Commands/Commands/utils.js
> +    setTimeout(() => resolve(arg), delayMS);
`arg` is undefined.

2017-02-24 20:34 UTC, nullpixel1 commented on Commands/Commands/utils.js
> +    setTimeout(() => resolve(arg), delayMS);
Whoops, that's because I removed the function return. I'm trying to write this code blind, as I haven't got my own instance up yet

2017-02-24 20:38 UTC, Arzte approved these changes

2017-02-24 20:40 UTC, nullpixel1 commented
I'm setting my own instance up right now, so I can actually see my stupid mistakes, it's hard to code blind :^3

2017-02-24 20:42 UTC, SirDoctors commented
Unrelated to the PR: @dougly I'd like to apolgize for pinging you in the commit, I meant to ping @SteamingMutt. Truly sorry to waste your time

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:50 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 02:53 UTC, SirDoctors commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove bot messages after a set interval](https://trello.com/c/CMNyuNHO/11-remove-bot-messages-after-a-set-interval)

2017-02-25 05:04 UTC, Dougly commented
😅

2017-02-25 12:35 UTC, Dougley approved these changes

2017-02-25 12:36 UTC, merged