Removing non-Custodian reports and cleaned up removing :report:
SteamingMutt/DiscordFeedback pull request #47
Opened 2017-06-28 21:18 UTC by LW001

Quick and easy change :^)

2017-06-30 21:31 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                    }, user)
What's user?
Is the intended behaviour here to only remove 1 reaction?

2017-06-30 21:31 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +                    msg.removeReaction({
Remove own reaction only?

2017-07-09 12:54 UTC, RSNFreud commented
Whats this waiting for?

2017-07-09 18:04 UTC, Dougley requested changes

2017-07-09 18:04 UTC, SteamingMutt commented on Commands/Commands/queue.js
> -                    }, bot.User)
`bot.User` would be the correct usage, refer to the [discordie documentation.](qeled.github.io/discordie/)

2017-07-09 18:05 UTC, SteamingMutt commented
Also, please resolve the merge conflicts.

2017-07-30 11:42 UTC, SteamingMutt commented
No activity for nearly a month, closing.

2017-07-30 11:42 UTC, closed without merging