Suggestion - !url
SteamingMutt/DiscordFeedback pull request #61
Opened 2017-07-19 10:42 UTC by LW001

Added !url UVID which parses an ID into a link. Also validates it to avoid typos.

2017-07-19 10:58 UTC, SirDoctors commented
Why is this needed, why does it need to interact with uservoice can't you just pass the Id to the end of a URL?

2017-07-19 19:00 UTC, Dougley requested changes
~~`Fix Travis` commit but Travis still fails lmao~~
Please fix your style issues first.

2017-07-24 06:09 UTC, SirDoctors commented on Commands/Commands/uservoice.js
>       } else {
ahem, you missed some useless stuff

2017-07-29 15:05 UTC, nullpixel requested changes

2017-07-29 15:05 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +    else msg.reply(`Please enter a Suggestion ID.`)
you should use the UVRegex:tm:

2017-07-29 22:41 UTC, LW001 commented on Commands/Commands/uservoice.js
> +    else msg.reply(`Please enter a Suggestion ID.`)
What's the use in taking a URL for a command that returns a URL though

2017-07-30 11:32 UTC, nullpixel commented on Commands/Commands/uservoice.js
> +    else msg.reply(`Please enter a Suggestion ID.`)
I mean to validate the ID

2017-07-30 11:33 UTC, Dougley submitted a review, later dismissed

2017-07-30 11:33 UTC, SteamingMutt commented on Commands/Commands/uservoice.js
> +    msg.channel.sendTyping()
Sending typing is trivial because race conditions, I'd say remove it.

2017-07-30 13:38 UTC, LW001 commented on Commands/Commands/uservoice.js
> +    else msg.reply(`Please enter a Suggestion ID.`)
We dropped that because UV is too slow ty

2017-07-30 15:07 UTC, nullpixel approved these changes

2017-07-30 15:07 UTC, nullpixel commented
I still don't see the point of this though

2017-07-30 15:09 UTC, merged