WIP: Autorole!
SteamingMutt/DiscordFeedback pull request #62
Opened 2017-07-30 18:06 UTC by nullpixel

**DO NOT MERGE:** waiting for total days to be added courtesy of Doug.

tested locally, works fine. fires every hour which can be tweaked. code is the best I could make it.

2017-07-30 18:07 UTC, nullpixel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Users earn new roles automatically based on daily activity](https://trello.com/c/dAz57hnM/57-users-earn-new-roles-automatically-based-on-daily-activity)

2017-07-30 20:58 UTC, LW001 commented on Utils/orwell.js
> +            if (member) { member.assignRole(role[1]); console.log(`Gave ${member.id} ${key}`) }
Shouldn't it rather send the user a message or log it in bot-log? Thought it doesn't do console outputs

2017-07-31 13:13 UTC, nullpixel commented
Almost done. See TODO in PR body.

2017-07-31 13:15 UTC, SteamingMutt commented
Style pls

2017-07-31 13:15 UTC, nullpixel commented
gottit.

2017-07-31 14:25 UTC, nullpixel commented
I've done all the stuff I said I would for this - awaiting dougley to add Consecutive Days to the database

2017-07-31 14:27 UTC, SteamingMutt commented
Style pls

2017-08-04 00:42 UTC, slice requested changes

2017-08-04 00:42 UTC, slice commented on Utils/orwell.js
> +          if (roleWeights === []) return; // has no roles :c
you can't compare arrays like this in javascript lol

```js
> [] === []
< false
```

use `roleWeights.length`

2017-08-04 01:10 UTC, SirDoctors commented on Utils/orwell.js
> +          if (roleWeights === []) return; // has no roles :c
fixed

2017-08-04 02:06 UTC, Arzte commented on roles.example.js
> +}
Why do all of these need to be separate files?

2017-08-04 02:11 UTC, SteamingMutt commented on roles.example.js
> +}
Because I said so.

2017-08-04 02:24 UTC, SirDoctors commented on roles.example.js
> +}
more files tho

2017-08-05 11:04 UTC, nullpixel commented
@SteamingMutt any idea when your thing will be done/

2017-08-05 21:46 UTC, nullpixel commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
we can make this a switch case.

2017-08-05 21:47 UTC, SirDoctors commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
... So why'd you merge it? lol

2017-08-05 21:48 UTC, nullpixel commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
because it's nothing with your pr, you followed the style of the old error catching, it was just a comment

2017-08-05 22:03 UTC, SirDoctors commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
And I was saying you could have done that on my pr, anyhow, we do this sort of thing on a lot of our commands, I wonder if there is something we can put in rather then these if statements everywhere? Of course This for example would need its own thing as its a "special" case.

2017-08-05 22:05 UTC, nullpixel commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
I think we should leave this as it is, then refactor all our error handling and huge if statements after, changing just this one doesn't make sense when we have a mess of them, along with messy callbacks and bad promise error catching 

2017-08-05 22:19 UTC, SirDoctors commented on Commands/Commands/queue.js
> +                } else if (e.statusCode === 422) {
Maybe after this pr gets merged we look into refactoring the mess that's been created? (Specifically the huge if and error code)

2017-08-08 16:23 UTC, Dougley requested changes
The initial custodian role is on an approval basis in the admin-queue, however, this doesn't seem to be the case.

2017-08-08 17:02 UTC, Dougley approved these changes

2017-08-08 17:04 UTC, merged