Check if dupe is in admin queue
SteamingMutt/DiscordFeedback pull request #97
Opened 2017-08-15 14:42 UTC by ThaTiemsz

This will return a message if someone does the !dupe command and the suggestion was already reported as a dupe.

Additionally I added a force flag one can use, which skips the message, cause maybe it's useful I don't know ¯\\\_(ツ)_/¯. I can remove it just as easily, if you guys think it's unneeded. Works as follows:

`!dupe https://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/16782913-video-calling http://feedback.discordapp.com/forums/326712-discord-dream-land/suggestions/10521852-add-video-chat -f`

2017-08-15 15:16 UTC, Dougley requested changes

2017-08-15 15:16 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +    if (results >= 1) {
`if (results > 0)`

2017-08-15 15:25 UTC, Dougley requested changes

2017-08-15 15:25 UTC, SteamingMutt commented on Commands/Commands/queue.js
> +    if (results > 0) {
`results.length` 👀

2017-08-17 12:45 UTC, ThaTiemsz commented
🙄

2017-08-17 12:55 UTC, Dougley approved these changes
👀

2017-08-17 12:55 UTC, merged